### ISSUE TITLE
Installing requirements.txt

### ISSUE THREAD

**Issue by ParisaO** [schroederdewitt/meme#1]
Hi,
I am trying to install the requirements.txt in anaconda prompt, and I get this error:
 The headers or library files could not be found for zlib,
      a required dependency when compiling Pillow from source.

      Please see the install instructions at:
         https://pillow.readthedocs.io/en/latest/installation.html

      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for Pillow

**Comment by schroederdewitt** [comment]
Hi Parisa, this seems to indicate you don't have the zlib-dev library installed.
Not sure what OS you are using, here are instructions for [zlib ubuntu](https://itsfoss.com/install-zlib-ubuntu/).

**Comment by ParisaO** [comment]
Thank you
